### ISSUE TITLE
Permission denied when reading files

### ISSUE THREAD

**Issue by SoloSynth1** [danielgatis/imgcat#4]
Using the snap package, `imgcat` returns permission denied error when a file is given as input in the argument.

However, it works fine when reading standard input (e.g. `cat <image>.jpg | imgcat`). Here is an example:

![imgcat](https://user-images.githubusercontent.com/17952490/130051972-6bd0bda2-d92a-4908-af86-f7aa3d615228.png)

I have tested it on Ubuntu 18.04 LTS & 20.04 LTS. Thanks for the follow-up in advance!

edit: typo

**Comment by danielgatis** [comment]
Have you already checked the file permissions?

```
ls -l yourfile.jpg
```

please paste the content here.

**Comment by SoloSynth1** [comment]
Sure, here it is; the image has 644 perm:
```bash
╭─user@userbox ~/Downloads 
╰─$ ls -l 5de6b0cecab8e70d1bd5e9111543a206.jpg 
-rw-r--r-- 1 user user 38915 Oct  8  2017 5de6b0cecab8e70d1bd5e9111543a206.jpg
```

**Comment by ngbusca** [comment]
I have the same issue. Installed imgcat via snap. `cat image.bmp | imgcat` works but `imgcat image.bmp` returns 403.

**Comment by danielgatis** [comment]
fixed next release

**Comment by sommerper** [comment]
Having the same issue. :(

Using `go version go1.17.7 linux/amd64`

Installed with `go install github.com/danielgatis/imgcat@latest`

Kernel `Linux version 5.15.15-76051515-generic (jenkins@warp.pop-os.org) (gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.37) #202201160435~1642693824~21.10~97db1bb SMP Thu Jan 20 17:35:05 U`

On `Pop!_OS 21.10`

**Comment by danielgatis** [comment]
I have no clue why this is happening. Any suggestion?

**Comment by sommerper** [comment]
Fortunately I don't know enough about Go. All I can say is that I tried `cat image.bmp | imgcat` - as mentioned above - and it also works on my system. It's not that bad since I can just make an alias but it is strange indeed.

**Comment by danielgatis** [comment]
@sommerper
Take a look at here:
https://github.com/danielgatis/imgcat/blob/master/main.go#L48

This is the line that opens the file. The file is open `readonly` it is a very strange error.

**Comment by sommerper** [comment]
weird. I tried giving combinations of root / $user ownership to imgcat and the image but still got `permission denied`.

As far as I can see `ioutil.ReadFile` is deprecated in favor of `os.ReadFile` but it shouldn't make a difference really.

**Comment by penguin359** [comment]
Same issue here, but I don't think it has anything to do with Go or the program itself. I suspect it's some AppArmor/SElinux restriction due to the jail that the snap runs in. If I try to have it open `/` or `/home`, it properly reports the error "is a directory", but when I have it open `/home/$USER`, it reports permission denied even though /home and /home/$USER allow world readability/access (i.e. 755 mode). The snap container restrictions need to be fixed, not the program itself.

**Comment by aminhusni** [comment]
Issue still exists

```
2022/08/18 05:43:20 failed to read the input file: open ed3e487f3a8e9712938cae5fcb8ac7b8.jpg: permission denied
panic: failed to read the input file: open ed3e487f3a8e9712938cae5fcb8ac7b8.jpg: permission denied

goroutine 1 [running]:
log.Panicf({0x542bed, 0x60}, {0xc00004ff30, 0x60, 0x644880})
	/opt/hostedtoolcache/go/1.17.7/x64/src/log/log.go:361 +0x67
main.read({0x7ffc7b6ba50a, 0xc000010050})
	/home/runner/work/imgcat/imgcat/main.go:50 +0xee
main.main()
	/home/runner/work/imgcat/imgcat/main.go:277 +0x85

```

**Comment by danielgatis** [comment]
@penguin359 
I just released version v1.0.14
When you get some free time, it would be nice if could test it. ;)

**Comment by ngbusca** [comment]
> @penguin359 I just released version v1.0.14 When you get some free time, it would be nice if could test it. ;)
> 
> [8f2acbf#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689R28](https://github.com/danielgatis/imgcat/commit/8f2acbf03dab176d1475e706618383245f550c6e#diff-42e26dc67aed8aa3edb2472b4403288c1699fb6dc47419b9a475f0f224fe4689R28)

I've just installed a fresh version via snap and still get the exact same issue

**Comment by sommerper** [comment]
Same here:
```
sudo snap refresh imgcat
snap "imgcat" has no updates available
```
